version: "3.8"

services:
  node-app:
    command: sh -c "cd /app && npm i && npm run dev -- -p 8080"
    image: node:18-alpine
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./ui:/app
      - node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

  django-app:
    command: sh -c "cd /app && pip install pipenv && pipenv install && pipenv run ./manage.py migrate && pipenv run ./manage.py runserver 0.0.0.0:8000"
    image: python:3.11-alpine
    environment:
      - POSTGRES_NAME=minesweeper
      - POSTGRES_USER=minesweeper
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CORS_HOST=http://localhost:8080
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - virtualenvs:/root/.local/share/virtualenvs/
      - django_cache:/app/cache

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=minesweeper
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=minesweeper
    volumes:
      - django_db_data:/var/lib/postgresql/data  # Persistent storage for Postgres data

volumes:
  django_db_data:
  django_cache:
  virtualenvs:
  node_modules: