# Generated by Django 4.2.11 on 2024-04-03 20:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'LOADING'), (2, 'PLAYING'), (3, 'WON'), (4, 'LOST')], default=server.models.WorldState['LOADING'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('debug_flags', models.CharField(max_length=255)),
                ('width', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(4)])),
                ('height', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(4)])),
                ('mine_count', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('cleared', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.SmallIntegerField()),
                ('y', models.SmallIntegerField()),
                ('state', models.IntegerField(choices=[(1, 'HIDDEN'), (2, 'SHOWN'), (3, 'EXPLOSION'), (4, 'FLAG')], default=server.models.TileState['HIDDEN'])),
                ('count', models.SmallIntegerField(default=0)),
                ('has_mine', models.BooleanField(default=False)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.world')),
            ],
            options={
                'unique_together': {('world', 'x', 'y')},
            },
        ),
    ]
